% Mitchell Grid (4x4) — Binary (BSF) encoding
% Generated by generate_grid_mdp.py
% Row fluents   : 2  (r1, r2)
% Column fluents: 2  (c1, c2)
% Total fluents : 4
% State space   : 16 binary codes, 16 valid
% Goal          : coor(1,4) = (0, 0, 1, 1)

state_fluent(r1).
state_fluent(r2).
state_fluent(c1).
state_fluent(c2).

action(left).
action(right).
action(up).
action(down).
action(stay).

utility(goal, 100).

% Reward model
% R(s,a): state-action pairs whose next state is the goal
goal :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), right.
goal :- not(r1(0)), r2(0), c1(0), c2(0), up.

% Encoding table
% r1  r2  c1  c2   state
% 0  0  0  0   coor(1,1)
% 0  0  0  1   coor(1,2)
% 0  0  1  0   coor(1,3)
% 0  0  1  1   coor(1,4)  GOAL
% 0  1  0  0   coor(2,1)
% 0  1  0  1   coor(2,2)
% 0  1  1  0   coor(2,3)
% 0  1  1  1   coor(2,4)
% 1  0  0  0   coor(3,1)
% 1  0  0  1   coor(3,2)
% 1  0  1  0   coor(3,3)
% 1  0  1  1   coor(3,4)
% 1  1  0  0   coor(4,1)
% 1  1  0  1   coor(4,2)
% 1  1  1  0   coor(4,3)
% 1  1  1  1   coor(4,4)

% Transition rules

% coor(1,1) = (0, 0, 0, 0)
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), not(c2(0)), right.
1.0::r2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), not(c2(0)), down.

% coor(1,2) = (0, 0, 0, 1)
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(c1(0)), c2(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), c2(0), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), c2(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), c2(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(c1(0)), c2(0), stay.

% coor(1,3) = (0, 0, 1, 0)
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), not(c2(0)), stay.

% coor(1,4) GOAL = (0, 0, 1, 1)
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), up.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), c1(0), c2(0), stay.

% coor(2,1) = (0, 1, 0, 0)
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), not(c2(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), not(c2(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(c1(0)), not(c2(0)), right.
1.0::r1(1) :- not(r1(0)), r2(0), not(c1(0)), not(c2(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), not(c2(0)), stay.

% coor(2,2) = (0, 1, 0, 1)
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), up.
1.0::r1(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), not(c1(0)), c2(0), stay.

% coor(2,3) = (0, 1, 1, 0)
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), left.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), up.
1.0::r1(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), down.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), stay.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), not(c2(0)), stay.

% coor(2,4) = (0, 1, 1, 1)
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), c2(0), left.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), c2(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), c2(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), c2(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), c2(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), c2(0), up.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), c2(0), up.
1.0::r1(1) :- not(r1(0)), r2(0), c1(0), c2(0), down.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), c2(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), c2(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), c1(0), c2(0), stay.
1.0::c1(1) :- not(r1(0)), r2(0), c1(0), c2(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), c1(0), c2(0), stay.

% coor(3,1) = (1, 0, 0, 0)
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), down.
1.0::r2(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), not(c2(0)), stay.

% coor(3,2) = (1, 0, 0, 1)
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), down.
1.0::r2(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), not(c1(0)), c2(0), stay.

% coor(3,3) = (1, 0, 1, 0)
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), left.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), right.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), right.
1.0::r2(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), up.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), down.
1.0::r2(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), down.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), stay.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), not(c2(0)), stay.

% coor(3,4) = (1, 0, 1, 1)
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), c2(0), left.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), c2(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), c2(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), c2(0), right.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), c2(0), right.
1.0::r2(1) :- r1(0), not(r2(0)), c1(0), c2(0), up.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), c2(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), c2(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), c2(0), down.
1.0::r2(1) :- r1(0), not(r2(0)), c1(0), c2(0), down.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), c2(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), c2(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), c1(0), c2(0), stay.
1.0::c1(1) :- r1(0), not(r2(0)), c1(0), c2(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), c1(0), c2(0), stay.

% coor(4,1) = (1, 1, 0, 0)
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), left.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), left.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), right.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), right.
1.0::c2(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), right.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), up.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), down.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), down.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), stay.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), not(c2(0)), stay.

% coor(4,2) = (1, 1, 0, 1)
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), c2(0), left.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), c2(0), left.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), c2(0), right.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), c2(0), right.
1.0::c1(1) :- r1(0), r2(0), not(c1(0)), c2(0), right.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), c2(0), up.
1.0::c2(1) :- r1(0), r2(0), not(c1(0)), c2(0), up.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), c2(0), down.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), c2(0), down.
1.0::c2(1) :- r1(0), r2(0), not(c1(0)), c2(0), down.
1.0::r1(1) :- r1(0), r2(0), not(c1(0)), c2(0), stay.
1.0::r2(1) :- r1(0), r2(0), not(c1(0)), c2(0), stay.
1.0::c2(1) :- r1(0), r2(0), not(c1(0)), c2(0), stay.

% coor(4,3) = (1, 1, 1, 0)
1.0::r1(1) :- r1(0), r2(0), c1(0), not(c2(0)), left.
1.0::r2(1) :- r1(0), r2(0), c1(0), not(c2(0)), left.
1.0::c2(1) :- r1(0), r2(0), c1(0), not(c2(0)), left.
1.0::r1(1) :- r1(0), r2(0), c1(0), not(c2(0)), right.
1.0::r2(1) :- r1(0), r2(0), c1(0), not(c2(0)), right.
1.0::c1(1) :- r1(0), r2(0), c1(0), not(c2(0)), right.
1.0::c2(1) :- r1(0), r2(0), c1(0), not(c2(0)), right.
1.0::r1(1) :- r1(0), r2(0), c1(0), not(c2(0)), up.
1.0::c1(1) :- r1(0), r2(0), c1(0), not(c2(0)), up.
1.0::r1(1) :- r1(0), r2(0), c1(0), not(c2(0)), down.
1.0::r2(1) :- r1(0), r2(0), c1(0), not(c2(0)), down.
1.0::c1(1) :- r1(0), r2(0), c1(0), not(c2(0)), down.
1.0::r1(1) :- r1(0), r2(0), c1(0), not(c2(0)), stay.
1.0::r2(1) :- r1(0), r2(0), c1(0), not(c2(0)), stay.
1.0::c1(1) :- r1(0), r2(0), c1(0), not(c2(0)), stay.

% coor(4,4) = (1, 1, 1, 1)
1.0::r1(1) :- r1(0), r2(0), c1(0), c2(0), left.
1.0::r2(1) :- r1(0), r2(0), c1(0), c2(0), left.
1.0::c1(1) :- r1(0), r2(0), c1(0), c2(0), left.
1.0::r1(1) :- r1(0), r2(0), c1(0), c2(0), right.
1.0::r2(1) :- r1(0), r2(0), c1(0), c2(0), right.
1.0::c1(1) :- r1(0), r2(0), c1(0), c2(0), right.
1.0::c2(1) :- r1(0), r2(0), c1(0), c2(0), right.
1.0::r1(1) :- r1(0), r2(0), c1(0), c2(0), up.
1.0::c1(1) :- r1(0), r2(0), c1(0), c2(0), up.
1.0::c2(1) :- r1(0), r2(0), c1(0), c2(0), up.
1.0::r1(1) :- r1(0), r2(0), c1(0), c2(0), down.
1.0::r2(1) :- r1(0), r2(0), c1(0), c2(0), down.
1.0::c1(1) :- r1(0), r2(0), c1(0), c2(0), down.
1.0::c2(1) :- r1(0), r2(0), c1(0), c2(0), down.
1.0::r1(1) :- r1(0), r2(0), c1(0), c2(0), stay.
1.0::r2(1) :- r1(0), r2(0), c1(0), c2(0), stay.
1.0::c1(1) :- r1(0), r2(0), c1(0), c2(0), stay.
1.0::c2(1) :- r1(0), r2(0), c1(0), c2(0), stay.
