% Mitchell Grid (2x3) — Binary (BSF) encoding
% Generated by generate_grid_mdp.py
% Row fluents   : 1  (r1)
% Column fluents: 2  (c1, c2)
% Total fluents : 3
% State space   : 8 binary codes, 6 valid
% Goal          : coor(1,3) = (0, 1, 0)

state_fluent(r1).
state_fluent(c1).
state_fluent(c2).

action(left).
action(right).
action(up).
action(down).
action(stay).

utility(goal, 100).

% Reward model
% R(s,a): state-action pairs whose next state is the goal
goal :- not(r1(0)), not(c1(0)), c2(0), right.
goal :- r1(0), c1(0), not(c2(0)), up.

% Encoding table
% r1  c1  c2   state
% 0  0  0   coor(1,1)
% 0  0  1   coor(1,2)
% 0  1  0   coor(1,3)  GOAL
% 1  0  0   coor(2,1)
% 1  0  1   coor(2,2)
% 1  1  0   coor(2,3)

% Transition rules

% coor(1,1) = (0, 0, 0)
1.0::c2(1) :- not(r1(0)), not(c1(0)), not(c2(0)), right.
1.0::r1(1) :- not(r1(0)), not(c1(0)), not(c2(0)), down.

% coor(1,2) = (0, 0, 1)
1.0::c1(1) :- not(r1(0)), not(c1(0)), c2(0), right.
1.0::c2(1) :- not(r1(0)), not(c1(0)), c2(0), up.
1.0::r1(1) :- not(r1(0)), not(c1(0)), c2(0), down.
1.0::c2(1) :- not(r1(0)), not(c1(0)), c2(0), down.
1.0::c2(1) :- not(r1(0)), not(c1(0)), c2(0), stay.

% coor(1,3) GOAL = (0, 1, 0)
1.0::c1(1) :- not(r1(0)), c1(0), not(c2(0)), left.
1.0::c1(1) :- not(r1(0)), c1(0), not(c2(0)), right.
1.0::c1(1) :- not(r1(0)), c1(0), not(c2(0)), up.
1.0::c1(1) :- not(r1(0)), c1(0), not(c2(0)), down.
1.0::c1(1) :- not(r1(0)), c1(0), not(c2(0)), stay.

% coor_invalid (0,3) — self-loop
1.0::c1(1) :- not(r1(0)), c1(0), c2(0), left.
1.0::c2(1) :- not(r1(0)), c1(0), c2(0), left.
1.0::c1(1) :- not(r1(0)), c1(0), c2(0), right.
1.0::c2(1) :- not(r1(0)), c1(0), c2(0), right.
1.0::c1(1) :- not(r1(0)), c1(0), c2(0), up.
1.0::c2(1) :- not(r1(0)), c1(0), c2(0), up.
1.0::c1(1) :- not(r1(0)), c1(0), c2(0), down.
1.0::c2(1) :- not(r1(0)), c1(0), c2(0), down.
1.0::c1(1) :- not(r1(0)), c1(0), c2(0), stay.
1.0::c2(1) :- not(r1(0)), c1(0), c2(0), stay.

% coor(2,1) = (1, 0, 0)
1.0::r1(1) :- r1(0), not(c1(0)), not(c2(0)), left.
1.0::r1(1) :- r1(0), not(c1(0)), not(c2(0)), right.
1.0::c2(1) :- r1(0), not(c1(0)), not(c2(0)), right.
1.0::r1(1) :- r1(0), not(c1(0)), not(c2(0)), down.
1.0::r1(1) :- r1(0), not(c1(0)), not(c2(0)), stay.

% coor(2,2) = (1, 0, 1)
1.0::r1(1) :- r1(0), not(c1(0)), c2(0), left.
1.0::r1(1) :- r1(0), not(c1(0)), c2(0), right.
1.0::c1(1) :- r1(0), not(c1(0)), c2(0), right.
1.0::c2(1) :- r1(0), not(c1(0)), c2(0), up.
1.0::r1(1) :- r1(0), not(c1(0)), c2(0), down.
1.0::c2(1) :- r1(0), not(c1(0)), c2(0), down.
1.0::r1(1) :- r1(0), not(c1(0)), c2(0), stay.
1.0::c2(1) :- r1(0), not(c1(0)), c2(0), stay.

% coor(2,3) = (1, 1, 0)
1.0::r1(1) :- r1(0), c1(0), not(c2(0)), left.
1.0::c2(1) :- r1(0), c1(0), not(c2(0)), left.
1.0::r1(1) :- r1(0), c1(0), not(c2(0)), right.
1.0::c1(1) :- r1(0), c1(0), not(c2(0)), right.
1.0::c1(1) :- r1(0), c1(0), not(c2(0)), up.
1.0::r1(1) :- r1(0), c1(0), not(c2(0)), down.
1.0::c1(1) :- r1(0), c1(0), not(c2(0)), down.
1.0::r1(1) :- r1(0), c1(0), not(c2(0)), stay.
1.0::c1(1) :- r1(0), c1(0), not(c2(0)), stay.

% coor_invalid (1,3) — self-loop
1.0::r1(1) :- r1(0), c1(0), c2(0), left.
1.0::c1(1) :- r1(0), c1(0), c2(0), left.
1.0::c2(1) :- r1(0), c1(0), c2(0), left.
1.0::r1(1) :- r1(0), c1(0), c2(0), right.
1.0::c1(1) :- r1(0), c1(0), c2(0), right.
1.0::c2(1) :- r1(0), c1(0), c2(0), right.
1.0::r1(1) :- r1(0), c1(0), c2(0), up.
1.0::c1(1) :- r1(0), c1(0), c2(0), up.
1.0::c2(1) :- r1(0), c1(0), c2(0), up.
1.0::r1(1) :- r1(0), c1(0), c2(0), down.
1.0::c1(1) :- r1(0), c1(0), c2(0), down.
1.0::c2(1) :- r1(0), c1(0), c2(0), down.
1.0::r1(1) :- r1(0), c1(0), c2(0), stay.
1.0::c1(1) :- r1(0), c1(0), c2(0), stay.
1.0::c2(1) :- r1(0), c1(0), c2(0), stay.
