% Mitchell Grid (6x6) — Binary (BSF) encoding
% Generated by generate_grid_mdp.py
% Row fluents   : 3  (r1, r2, r3)
% Column fluents: 3  (c1, c2, c3)
% Total fluents : 6
% State space   : 64 binary codes, 36 valid
% Goal          : coor(1,6) = (0, 0, 0, 1, 0, 1)

state_fluent(r1).
state_fluent(r2).
state_fluent(r3).
state_fluent(c1).
state_fluent(c2).
state_fluent(c3).

action(left).
action(right).
action(up).
action(down).
action(stay).

utility(goal, 100).

% Reward model
% R(s,a): state-action pairs whose next state is the goal
goal :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
goal :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.

% Encoding table
% r1  r2  r3  c1  c2  c3   state
% 0  0  0  0  0  0   coor(1,1)
% 0  0  0  0  0  1   coor(1,2)
% 0  0  0  0  1  0   coor(1,3)
% 0  0  0  0  1  1   coor(1,4)
% 0  0  0  1  0  0   coor(1,5)
% 0  0  0  1  0  1   coor(1,6)  GOAL
% 0  0  1  0  0  0   coor(2,1)
% 0  0  1  0  0  1   coor(2,2)
% 0  0  1  0  1  0   coor(2,3)
% 0  0  1  0  1  1   coor(2,4)
% 0  0  1  1  0  0   coor(2,5)
% 0  0  1  1  0  1   coor(2,6)
% 0  1  0  0  0  0   coor(3,1)
% 0  1  0  0  0  1   coor(3,2)
% 0  1  0  0  1  0   coor(3,3)
% 0  1  0  0  1  1   coor(3,4)
% 0  1  0  1  0  0   coor(3,5)
% 0  1  0  1  0  1   coor(3,6)
% 0  1  1  0  0  0   coor(4,1)
% 0  1  1  0  0  1   coor(4,2)
% 0  1  1  0  1  0   coor(4,3)
% 0  1  1  0  1  1   coor(4,4)
% 0  1  1  1  0  0   coor(4,5)
% 0  1  1  1  0  1   coor(4,6)
% 1  0  0  0  0  0   coor(5,1)
% 1  0  0  0  0  1   coor(5,2)
% 1  0  0  0  1  0   coor(5,3)
% 1  0  0  0  1  1   coor(5,4)
% 1  0  0  1  0  0   coor(5,5)
% 1  0  0  1  0  1   coor(5,6)
% 1  0  1  0  0  0   coor(6,1)
% 1  0  1  0  0  1   coor(6,2)
% 1  0  1  0  1  0   coor(6,3)
% 1  0  1  0  1  1   coor(6,4)
% 1  0  1  1  0  0   coor(6,5)
% 1  0  1  1  0  1   coor(6,6)

% Transition rules

% coor(1,1) = (0, 0, 0, 0, 0, 0)
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.

% coor(1,2) = (0, 0, 0, 0, 0, 1)
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(1,3) = (0, 0, 0, 0, 1, 0)
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(1,4) = (0, 0, 0, 0, 1, 1)
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.

% coor(1,5) = (0, 0, 0, 1, 0, 0)
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(1,6) GOAL = (0, 0, 0, 1, 0, 1)
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (0,6) — self-loop
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (0,7) — self-loop
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.

% coor(2,1) = (0, 0, 1, 0, 0, 0)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor(2,2) = (0, 0, 1, 0, 0, 1)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(2,3) = (0, 0, 1, 0, 1, 0)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(2,4) = (0, 0, 1, 0, 1, 1)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.

% coor(2,5) = (0, 0, 1, 1, 0, 0)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(2,6) = (0, 0, 1, 1, 0, 1)
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (1,6) — self-loop
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (1,7) — self-loop
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::r3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.

% coor(3,1) = (0, 1, 0, 0, 0, 0)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor(3,2) = (0, 1, 0, 0, 0, 1)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(3,3) = (0, 1, 0, 0, 1, 0)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(3,4) = (0, 1, 0, 0, 1, 1)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.

% coor(3,5) = (0, 1, 0, 1, 0, 0)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(3,6) = (0, 1, 0, 1, 0, 1)
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (2,6) — self-loop
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (2,7) — self-loop
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.

% coor(4,1) = (0, 1, 1, 0, 0, 0)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor(4,2) = (0, 1, 1, 0, 0, 1)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(4,3) = (0, 1, 1, 0, 1, 0)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(4,4) = (0, 1, 1, 0, 1, 1)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.

% coor(4,5) = (0, 1, 1, 1, 0, 0)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(4,6) = (0, 1, 1, 1, 0, 1)
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (3,6) — self-loop
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (3,7) — self-loop
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::r2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::r3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- not(r1(0)), r2(0), r3(0), c1(0), c2(0), c3(0), stay.

% coor(5,1) = (1, 0, 0, 0, 0, 0)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor(5,2) = (1, 0, 0, 0, 0, 1)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(5,3) = (1, 0, 0, 0, 1, 0)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(5,4) = (1, 0, 0, 0, 1, 1)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.

% coor(5,5) = (1, 0, 0, 1, 0, 0)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(5,6) = (1, 0, 0, 1, 0, 1)
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (4,6) — self-loop
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (4,7) — self-loop
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), not(r3(0)), c1(0), c2(0), c3(0), stay.

% coor(6,1) = (1, 0, 1, 0, 0, 0)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor(6,2) = (1, 0, 1, 0, 0, 1)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.

% coor(6,3) = (1, 0, 1, 0, 1, 0)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.

% coor(6,4) = (1, 0, 1, 0, 1, 1)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), not(c1(0)), c2(0), c3(0), stay.

% coor(6,5) = (1, 0, 1, 1, 0, 0)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.

% coor(6,6) = (1, 0, 1, 1, 0, 1)
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (5,6) — self-loop
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (5,7) — self-loop
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::r3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), not(r2(0)), r3(0), c1(0), c2(0), c3(0), stay.

% coor_invalid (6,0) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor_invalid (6,1) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), not(c2(0)), c3(0), stay.

% coor_invalid (6,2) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), not(c3(0)), stay.

% coor_invalid (6,3) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), not(c1(0)), c2(0), c3(0), stay.

% coor_invalid (6,4) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), not(c3(0)), stay.

% coor_invalid (6,5) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (6,6) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (6,7) — self-loop
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), not(r3(0)), c1(0), c2(0), c3(0), stay.

% coor_invalid (7,0) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), not(c3(0)), stay.

% coor_invalid (7,1) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), not(c2(0)), c3(0), stay.

% coor_invalid (7,2) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), not(c3(0)), stay.

% coor_invalid (7,3) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), r3(0), not(c1(0)), c2(0), c3(0), stay.

% coor_invalid (7,4) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), not(c3(0)), stay.

% coor_invalid (7,5) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), not(c2(0)), c3(0), stay.

% coor_invalid (7,6) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), not(c3(0)), stay.

% coor_invalid (7,7) — self-loop
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), left.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), right.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), up.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), down.
1.0::r1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::r2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::r3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c1(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c2(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
1.0::c3(1) :- r1(0), r2(0), r3(0), c1(0), c2(0), c3(0), stay.
